version: '2'

networks:
  default:
    external:
      name: raisebook_raisebook-dev-net

volumes:
  elixir_deps:
    driver: local
  elixir_build:
    driver: local

services:
  qbot: &qbot
    build:
      context: .
      dockerfile: Dockerfile
    image: qbot
    environment:
      MIX_ENV:
    env_file:
      - ./development.env
    volumes:
      - .:/app
      - elixir_deps:/app/deps
      - elixir_build:/app/_build
  qbot-build-release:
    <<: *qbot
    env_file:
      - ./build-prod.env

  deployment:
    image: 038451313208.dkr.ecr.ap-southeast-2.amazonaws.com/deploy:b3084064dfb29773e1a333bd7deebf8dece5b3eb
    volumes:
      - .:/app
    tmpfs:
      - /tmp
    environment:
      ECS_CLUSTER:
      DOCKER_TAG_PREFIX:
      BUILDKITE_COMMIT:
      BUILDKITE_BUILD_CREATOR:
      ROLLBAR_ACCESS_TOKEN_KMS: "AQECAHgBe/Bo6N6P3DZu2j8rSbOworqekgIES5evTHicjBhp6AAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAwpbxxeLfqMGD2ajgIBEIA7P7Oi/L6t8TGkvLNNZev0u3WJj6pJE+G7CPii1QwihGLGqyEfbC1NI84H9nH5eCq6ff6GsPJoGUM3lXo="
