version: '2'

networks:
  default:
    external:
      name: raisebook_raisebook-dev-net

services:
  qbot: &qbot
    build:
      context: .
      dockerfile: Dockerfile
    image: qbot
    env_file:
      - ./development.env
    volumes:
      - .:/app

  qbot-build-release:
    <<: *qbot
    env_file:
      - ./build-prod.env
