version: '2'

networks:
  default:
    external:
      name: raisebook_raisebook-dev-net

services:
  qbot: &qbot
    build:
      context: .
      dockerfile: Dockerfile
    image: qbot
    env_file:
      - ./development.env
    volumes:
      - .:/app

  qbot-build-release:
    <<: *qbot
    env_file:
      - ./build-prod.env

  deployment:
    image: raisebook/deploy:daecb6009f57a6718804da86e020e6bb3c62808f
    volumes:
      - .:/app
    tmpfs:
      - /tmp
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      AWS_DEFAULT_REGION:
      ECS_CLUSTER:
      DOCKER_TAG_PREFIX:
      BUILDKITE_COMMIT:
      BUILDKITE_BUILD_CREATOR:
      ROLLBAR_ACCESS_TOKEN_KMS: "AQECAHgBe/Bo6N6P3DZu2j8rSbOworqekgIES5evTHicjBhp6AAAAH4wfAYJKoZIhvcNAQcGoG8wbQIBADBoBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAwpbxxeLfqMGD2ajgIBEIA7P7Oi/L6t8TGkvLNNZev0u3WJj6pJE+G7CPii1QwihGLGqyEfbC1NI84H9nH5eCq6ff6GsPJoGUM3lXo="
