steps:
  - name: ":elixir: Tests"
    command: '.buildkite/test-and-lint.sh'

  - block: ":rotating_light: Deploy :rotating_light:"
    branches: 'master'
    fields:
      - select: "ECS Cluster"
        key: ecs-cluster
        required: true
        options:
         - label: "production"
           value: "default"
         - label: "compliance"
           value: "compliance"

  - name: ":elixir: Build Release Image :docker:"
    command: ".buildkite/build-release-image.sh"
    branches: 'master'

  - wait:

  - name: ":ecs: Deploy"
    command: ".buildkite/deploy-to-ecs.sh"
    branches: 'master'
